# ============================================================
# RandomChunk
# Author: KingBrezz
# Paper 26.2 / Java 25
# ============================================================

# Languages:
# en = English
# id = Indonesian
# vi = Vietnamese
# th = Thai
# ru = Russian
# de = German

language: en

settings:

  # false = plugin tidak otomatis aktif setelah restart.
  enabled-on-start: false

  # true = setiap chunk hanya diproses satu kali.
  # /randomchunk reset untuk mengulang semua chunk.
  process-once: true

  # Air tetap air.
  replace-air: false

  # Bedrock ikut diganti.
  replace-bedrock: true

  # false = replacement tanpa physics.
  apply-physics: false

  # Jumlah chunk yang boleh diproses bersamaan.
  max-active-chunks: 1


# ============================================================
# SPEED
# ============================================================
#
# FAST
# NORMAL
# SLOW
# CUSTOM
#
# DEFAULT = NORMAL
#
# FAST:
#   16384 block/tick
#
# NORMAL:
#   4096 block/tick
#
# SLOW:
#   512 block/tick
#
# CUSTOM:
#   menggunakan blocks-per-tick
#

speed:

  preset: NORMAL

  # Hanya digunakan jika preset = CUSTOM.
  blocks-per-tick: 4096

  # Jika TPS turun, plugin otomatis menggunakan
  # slow-mode-blocks-per-tick.
  adaptive-tps: true

  # Batas TPS untuk mengaktifkan slow mode.
  minimum-tps: 18.0

  # Kecepatan ketika TPS rendah.
  slow-mode-blocks-per-tick: 512


# ============================================================
# WORLDS
# ============================================================

worlds:

  # [] = semua world.
  #
  # Contoh:
  #
  # enabled:
  #   - world
  #   - world_nether
  #
  enabled: []


# ============================================================
# STORAGE
# ============================================================

storage:

  # Menyimpan chunk yang sudah selesai diproses.
  persistent: true

  # Simpan data setiap X chunk.
  save-every-chunks: 1
